[package]
name = "hello_lib_skyler_test"
version = "0.1.0"
edition = "2024"
description = "A test library I made"
license = "MIT"
repository = "https://github.com/DOEfodder/testFunction" 

[dependencies]
